#!/bin/sh /etc/rc.common
# Copyright 2024 Tailscale for ZLAN9809M Project
# Licensed under MIT License

USE_PROCD=1
START=96
STOP=11

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/mqtt-daemon
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    killall mqtt-daemon 2>/dev/null
}
